group: travis_latest
sudo: required
language: node_js
node_js:
 - "8"
env:
  global:
    - DOCKER_COMPOSE_VERSION=1.17.1

before_install:
  - sudo service postgresql stop
  - sudo apt-get update
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-ce
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
  - docker-compose build
  - docker-compose -p judgecompose up -d

before_script:
  - docker exec judgecompose_api_1 scripts/wait-for-it.sh -t 180 api:3737 -- npm run seedlangs

script:
  - docker kill judgecompose_api_1
  - mkdir -p coverage
  - |
    docker run -t --env-file test.env \
    -v "$PWD/coverage:/usr/src/judge-api/coverage" \
    --network judgecompose_default \
    --env "DEBUG=test:* JUDGEAPI_HOST=api JUDGEAPI_PORT=2222" codingblocks/judge-api \
    npm run cover

after_success:
  - bash <(curl -s https://codecov.io/bash)
